env:
  global:
    - CC_TEST_REPORTER_ID=bd05ef1fea94a4d280d53d9db7de305167e25cdb1b5db7f030516f96edbdee74

language: php

php:
 - '5.6'
 - '7.3'
 # - nightly # Not supported by PHPUnit

# Commands to be run before your environment runs.
before_script:
 - composer self-update
 - composer update --no-interaction
 - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
 - chmod +x ./cc-test-reporter
 - ./cc-test-reporter before-build

# Commands you want to run that will verify your build.
# Do not use the customized ./phpunit as retrocompatibility must be
# generated and committed 
script: ./vendor/bin/phpunit --coverage-clover=coverage.xml --testsuite=all_tests

after_script:
 - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
 - bash <(curl -s https://codecov.io/bash)

# Handle git submodules yourself. https://stackoverflow.com/questions/15674064/how-to-fix-a-permission-denied-publickey-error-for-a-git-submodule-update-in-t
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
