#!/usr/bin/env php
<?php

if (PHP_VERSION_ID < 70000) {
    // generate PHP 5.6 classes
    system(__DIR__ . '/retrocompatibility_generator');
}

if (preg_match("/^(.+\/)?php\d+.\d+$/", $_SERVER['_'])) {
    $php_bin = $_SERVER['_'];
}
else {
    $php_bin = '';
}

// remove the ./phpunit
$args = $argv;
array_shift($args);

if (PHP_VERSION_ID >= 70000) {
    $config = 'tests/phpunit.xml';    
}
else {
    $config = 'tests/phpunit_5.6.xml';
}

$version = explode('.',phpversion());
$version = $version[0] . '.' . $version[1];

$phpunit_path = './vendor_'.$version.'/bin/phpunit';

if ( ! is_file($phpunit_path)) {
    system($php_bin.' ./composer install');
}

// var_dump($phpunit_path);
system(
    $php_bin.' '.$phpunit_path.' --config ' . $config
    . ' ' . implode(' ', $args) . ' ' 
    . ' --colors=always'
);
